
variables:
  REPOSITORY: 993748048099/cicd
  TAG: 1.0
build_image:
  image: docker
  services:
    - docker:26.1.1-dind
  variables:
    DOCKER_TLS_CERTIFICATE: '/certs'
  before_script:
    - docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD 
  script:
    - echo 'docker image create'
    - docker build -t $REPOSITORY:$TAG .
    - docker push $REPOSITORY:$TAG