version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust the Node.js version as needed

  pre_build:
    commands:
      - npm install -g typescript

  build:
    commands:
      - npm install
      - npm run build   # Run TypeScript compiler to build the project

  post_build:
    commands:
      - echo done   # Run tests or any additional post-build steps
  
artifacts:
    files:
      - "**/*"