version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust the Node.js version as needed

  pre_build:
    commands:
      - npm install -g typescript

  build:
    commands:
      - npm install
      - npm run build   # Run TypeScript compiler to build the project
  post_build:
    commands:
      - echo "Copy artifacts..."
      - cp -r ./build/* .  # Copy compiled JavaScript files (adjust path if needed)

artifacts:
  # Include compiled JavaScript files and potentially other build artifacts
  files:
    - '**/*.js'  # Include all JavaScript files
    - 'package*.json'  # Include package.json and other relevant files (optional)
